#!/bin/sh

echo "*****Running spotless apply******"

./gradlew spotlessApply

if ! git diff --quiet; then  
  echo "Spotless applied changes. Please stage them and commit again."  
  exit 1  
fi 

echo "*****Spotless apply completed successfully******"

exit 0
