#!/bin/sh

echo "*****Running spotless apply******"

./gradlew spotlessCheck || {
  echo "Spotless check failed. Please fix the issues before pushing."
  exit 1
}

if ! git diff --quiet; then  
  echo "Spotless applied changes. Please stage them and commit again."  
  exit 1  
fi 

echo "*****Spotless apply completed successfully******"

exit 0
