name: Run Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.gitignore'
      - 'LICENSE'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/**'
      - 'renovate.json'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.gitignore'
      - 'LICENSE'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/**'
      - 'renovate.json'

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: 'temurin'

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        run: ./gradlew test --rerun-tasks --no-daemon